### ISSUE TITLE
Correct npm install command

### ISSUE THREAD

**Issue by Taskkill** [jdalrymple/node-gitlab-api#1]
Hello,
I assume your package on npm is node-gitlab-api. Shouldn't be it installed like npm install node-gitlab-api instead of npm install gitlab?
Same with require('gitlab-api')
Thanks for your job and have a good day.

**Comment by jdalrymple** [comment]
It is! I forgot to update the documentation. I'll make sure to fix it today!

**Comment by jdalrymple** [comment]
Fixed with v1.0.10!
