### ISSUE TITLE
Unable to get repository files with ProjectRepository.showFile(...)

### ISSUE THREAD

**Issue by sparcs360** [jdalrymple/node-gitlab-api#11]
Hi

(first off, thanks for sharing the code!)

I'm not able to get a repository file using the `ProjectRepository.showFile` implementation against my private GitLab v9.5 setup.  The modified implementation below (based on the [GitLab API docs](https://docs.gitlab.com/ee/api/repository_files.html)) is working for me.

Note that the `page` option has to be forced to 'true' to prevent `BaseModel` from attempting to read all pages (which aren't there).

```javascript
  showFile(projectId, ref, filePath) {
    const pId = Utils.parse(projectId);

    return this.get(`projects/${pId}/repository/files/${filePath}`, {"ref": ref, "page": true});
  }
```

**Comment by jdalrymple** [comment]
Hey! Weird, I'll make your suggested changes and see if I can narrow down why the paging acts weird with this end point

**Comment by jdalrymple** [comment]
Pushed an update in the latest commit! Tell me if it works ok for you!

**Comment by sparcs360** [comment]
Great success!  Thanks @jdalrymple
