### ISSUE TITLE
Error: `options is not defined`

### ISSUE THREAD

**Issue by clthck** [jdalrymple/node-gitlab-api#13]
- [`ProjectRepository::showFile`](https://github.com/jdalrymple/node-gitlab-api/blob/1.3.0/src/Models/ProjectRepository.js#L92)
- [`ProjectRepository::showFileRaw`](https://github.com/jdalrymple/node-gitlab-api/blob/1.3.0/src/Models/ProjectRepository.js#L98)

**Comment by jdalrymple** [comment]
Fixing now! sorry :(

**Comment by jdalrymple** [comment]
Published!

**Comment by clthck** [comment]
Great! Thanks for quick response!
