### ISSUE TITLE
Default value for `options`

### ISSUE THREAD

**Issue by clthck** [jdalrymple/node-gitlab-api#15]
- `BaseModel::get`
- `BaseModel::post`
- `BaseModel::put`
...

Previously, it was checking if `options` is truthy, but now it's not, which in turn causes an error.

> TypeError: Cannot read property 'page' of undefined

Can we assign default values for `options` parameter?

**Comment by jdalrymple** [comment]
will fix!

**Comment by jdalrymple** [comment]
Pushed in v1.3.2
