### ISSUE TITLE
Support for custom_attributes

### ISSUE THREAD

**Issue by beeing** [jdalrymple/node-gitlab-api#16]
Hi, there's new API for /users/:id/custom_attributes and also for groups and projects as well.

Will be great if this can be added.

Thanks.

**Comment by jdalrymple** [comment]
Will add to the v2.0.1rc.1 :)

**Comment by jdalrymple** [comment]
Added the functionality in the recent commit, just need to brush up some of the documentation before the release

**Comment by jdalrymple** [comment]
Just released!
