### ISSUE TITLE
Accept MR

### ISSUE THREAD

**Issue by vlaraort** [jdalrymple/node-gitlab-api#17]
Hi!

This endpoint is missing, can it be added?

https://docs.gitlab.com/ce/api/merge_requests.html#accept-mr

Thanks!

**Comment by jdalrymple** [comment]
Will add to v2.0.1rc.1!

**Comment by jdalrymple** [comment]
Added the functionality in the recent commit, just need to brush up some of the documentation before the release

**Comment by jdalrymple** [comment]
Just released!
