### ISSUE TITLE
MergeRequest Comment url is incorrect

### ISSUE THREAD

**Issue by SimonGrahamZtr** [jdalrymple/node-gitlab-api#20]
Currently creating a note for a mergeRequest is posting to

'projects/:id/merge_requests/:merge_request_iid/comment'

however, it should be:

POST /projects/:id/merge_requests/:merge_request_iid/notes

ref: https://docs.gitlab.com/ce/api/notes.html

**Comment by jdalrymple** [comment]
Oops! Will fix soon, thanks!

**Comment by jdalrymple** [comment]
Didn't notice originally, but fixed already in the pre-release! Will be pushed with v2 release :)

**Comment by jdalrymple** [comment]
Just released!

**Comment by SimonGrahamZtr** [comment]
Awesome thanks! Cheers for fixing so fast! Keep up the good work.
