### ISSUE TITLE
`parse` question

### ISSUE THREAD

**Issue by arsdehnel** [jdalrymple/node-gitlab-api#24]
I'm trying to call `const projects = await gitlab.groups.projects.all( 'cpd' );` and I'm getting `http://<gitlab hostname>/api/v4/groups/NaN/projects` as the request URL because I'm passing the name as the parameter [as the gitlab docs say we can](https://docs.gitlab.com/ee/api/groups.html#list-a-group-39-s-projects) but the `parse` function is falling through to the `parseInt()` bit.  Should that be wrapped in a try/catch or something so that if the parseInt fails (or returns `NaN`) we get back the original value?

**Comment by jdalrymple** [comment]
Hey! Is that the name of your project in gitlab? According to the docs it's the url encoded name like 'arsdehnel/cpd'. They explain it better here https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding

Hope that helps!

**Comment by arsdehnel** [comment]
But I'm hitting https://docs.gitlab.com/ee/api/groups.html#list-a-group-39-s-projects which only required the `groupId` to be provided:

```
GET /groups/:id/projects
```

And the `id` parameter is described as 
> The ID or URL-encoded path of the group owned by the authenticated user

And since it's a group just a single string with no `/` is valid/expected.

**Comment by jdalrymple** [comment]
hmm, that does make sense. Il look into it!

**Comment by jdalrymple** [comment]
Found the problem! Ill fix it soon!

**Comment by jdalrymple** [comment]
I think my recent push fixed this. Will test further tomorrow if you dont beat me to it!

**Comment by jdalrymple** [comment]
Pushed!
