### ISSUE TITLE
Merge Request API

### ISSUE THREAD

**Issue by fewieden** [jdalrymple/node-gitlab-api#25]
Is there a reason, that the merge request api doesn't get exposed?

The model directory exports it here https://github.com/jdalrymple/node-gitlab-api/blob/master/src/Models/index.js#L14

But here in the API it gets not imported https://github.com/jdalrymple/node-gitlab-api/blob/master/src/API.js#L2

And so it is not available here https://github.com/jdalrymple/node-gitlab-api/blob/master/src/API.js#L33-L37

**Comment by fewieden** [comment]
So by importing mergerequest model and exposing it to the api I can use it.

Only issue was that there is a first parameter https://github.com/jdalrymple/node-gitlab-api/blob/master/src/Models/MergeRequests.js#L4 projectId which doesn't get used. Is there a reason for it, as all the other endpoints I used don't have it.

**Comment by arsdehnel** [comment]
Seems like exposing that makes sense, otherwise not sure how you'd use it.  And I'd agree that the first parameter seems unnecessary.  There are some more options for the MR API (like this one https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests) that need it but the `all()` call doesn't have an option for it.

**Comment by fewieden** [comment]
@arsdehnel that one is olready in this model https://github.com/fewieden/node-gitlab-api/blob/master/src/Models/ProjectMergeRequests.js#L27

**Comment by arsdehnel** [comment]
Missed that one, sorry about that.

**Comment by jdalrymple** [comment]
Just merged into 2.2.0 :)

**Comment by fewieden** [comment]
Do you have an eta when this will be published to npm, as i have some building issues in my automatic pipelines with my fork? Just need to know if I have to workaround it or it will be available in couple of days.

Thanks in advance

**Comment by jdalrymple** [comment]
Yup! Will be publishing today, just need to test that parse change before I publish
