### ISSUE TITLE
Add projects statistics API

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#29]
Support the `statistics=yes` parameter for the GitLab API: 
https://docs.gitlab.com/ce/api/projects.html

**Comment by max-wittig** [comment]
Okay I've just noticed that you can specify custom options

**Comment by jdalrymple** [comment]
Is there anyway I could make that clearer ?

**Comment by miksonx** [comment]
@max-wittig @jdalrymple  how can you specify "custom options" to get project statistics?
Thank you

**Comment by jdalrymple** [comment]
```javascript
const allProjectsWithStats = await Projects.all({
statistics: true
});
```
