### ISSUE TITLE
Way to access the GitLab version via API?

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#31]
Is the version API exposed in any way?
See: https://docs.gitlab.com/ce/api/version.html

**Comment by jdalrymple** [comment]
Not yet, would be an easy PR though

**Comment by jdalrymple** [comment]
Just released. Hope this is what you were looking for :)

**Comment by max-wittig** [comment]
Awesome thanks 😃

**Comment by max-wittig** [comment]
@jdalrymple Could you help me with the usage. I've tried 
`gitlab.version.show()` and version seems to be undefined. What did I do wrong?

**Comment by jdalrymple** [comment]
It's possible I made a mistake with the url :( I'll look tonight

**Comment by jdalrymple** [comment]
Missed part of the commit lol Fixing now.

**Comment by jdalrymple** [comment]
Should be fixed in the latest release :)
