### ISSUE TITLE
Custom Attributes API

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#32]
Do you provide an abstraction layer for [GitLab custom attributes](https://docs.gitlab.com/ee/api/custom_attributes.html#custom-attributes-api)?

**Comment by jdalrymple** [comment]
Yes its currently supported. It can be accessed by [resource].customAttributes.[action] ie. projects.customAttributes.show()

**Comment by max-wittig** [comment]
Thanks 😃

**Comment by max-wittig** [comment]
It seems like `customAttributes` is always undefined for me. I tried to get a custom attribute from a user.
@jdalrymple
