### ISSUE TITLE
es5 build issue

### ISSUE THREAD

**Issue by fewieden** [jdalrymple/node-gitlab-api#33]
The es5 version still has es6 features like async/await  included. Looks like a misconfiguration of babel.

e.g. `BaseModel.js` => `async function getAllPages...`

I wanted to use this in an aws lambda function which supports only node 6

**Comment by jdalrymple** [comment]
I'll give it a look! Probably like you said, just incorrect babel config

**Comment by jdalrymple** [comment]
I think I found the problem !

**Comment by jdalrymple** [comment]
Nope that didnt work. Not sure how to fix this. I added

`--preset=es2015,es2016` 

to the package.json to go from current code down to es6 and then es5 but that didnt work :( Any other ideas?

**Comment by fewieden** [comment]
by using https://babeljs.io/repl/ and preset es2017 it looks like its converting the async/await to generators

**Comment by jdalrymple** [comment]
Ahh, ill try including es2017

**Comment by jdalrymple** [comment]
Merged! Will release today

**Comment by fewieden** [comment]
Apparently this didn't fix the issue completely. `async/await` got now replaced with generators, but when I run my automated tests I get the following error `ReferenceError: regeneratorRuntime is not defined` which is related to the babel transformation

**Comment by jdalrymple** [comment]
I think we just need to include the runtime transformation plugin ?,  I thought about multiple babelrc files but apparently that's not possible. I'll try adding the plugin and see if that helps

**Comment by fewieden** [comment]
Looks like there is an option in babel 7 https://github.com/babel/babel/pull/6133/files

**Comment by fewieden** [comment]
Did you had a chance to test the runtime transformation plugin?

**Comment by jdalrymple** [comment]
Looking now!

**Comment by jdalrymple** [comment]
The new version of babel supports multiple babel files, so i've implemented that, but ive run into an issue with the new version of transform-runtime plugin used to transpile the generators. Submitted a bug hopefully it will be resolved soon!

**Comment by jdalrymple** [comment]
I think its good now. Want to give it a check? Its the es5-support-fixes branch

**Comment by jdalrymple** [comment]
Can anyone verify?

**Comment by jdalrymple** [comment]
Going to assume things are working correctly here, will merge in the fixes for the next release

**Comment by jdalrymple** [comment]
Can be viewed in branch 2.3.0-rc.1

**Comment by jdalrymple** [comment]
released under 3.0.0-rc.2
