### ISSUE TITLE
Inconsistent project name

### ISSUE THREAD

**Issue by Infinitetutts** [jdalrymple/node-gitlab-api#34]
Greetings :),

I am having an issue with getting a project from Gitlab. It sends Nginx to different project names, which therefor errors sometimes.

Code:
```
   let project = await GitlabAPI.projects.show('wp/ds-wp-nginx-fpm');
   return project;
```

Nginx logs:
> 111.111.29.83 - - [23/Jan/2018:15:32:16 +0000] "GET /api/v4/projects/wp%2Fds-wp-nginx-fpm HTTP/1.1" 200 1917 "-" "-"
> 111.111.29.84 - - [23/Jan/2018:15:32:18 +0000] "GET /api/v4/projects/wp/ds-wp-nginx-fpm HTTP/1.1" 404 25 "-" "-"
> 111.111.29.83 - - [23/Jan/2018:15:32:21 +0000] "GET /api/v4/projects/wp%2Fds-wp-nginx-fpm HTTP/1.1" 200 1917 "-" "-"

`node version 8.3.0`
 ` "node-gitlab-api": "^2.2.1"`

**Comment by jdalrymple** [comment]
Hmm, thats odd. Same code results in different urls being generated? Ill do some tests locally and see if i can consistently recreate the problem!

**Comment by jdalrymple** [comment]
I havent been able to recreate the problem thus far :(

Before the url is created, the endings are encoded by the parse function in utils:

```
function parse(value) {
  if (Number.isInteger(value)) return value;

  return encodeURIComponent(value);
}
```
hmm, ill keep debugging

**Comment by Infinitetutts** [comment]
Sorry brotha ! There is an Nginx proxy that I was made aware of which is causing the issue! If I hit the Gitlab server directly it works :)

**Comment by jdalrymple** [comment]
phewf!
