### ISSUE TITLE
How to list a specific branches commits ?

### ISSUE THREAD

**Issue by Infinitetutts** [jdalrymple/node-gitlab-api#36]
Code:
let listCommits= await GitlabAPI.projects.repository.commits.all('gg/asdf');

Can one list a specific branches commits ? Sorry for messaging you here <3

**Comment by jdalrymple** [comment]
Hmm, i dont know if that is supported, but it wouldnt be hard to add!

**Comment by Infinitetutts** [comment]
Thank u :D! I will figure out a way  💃

**Comment by jdalrymple** [comment]
Just read the correct way of doing it!

 let listCommits= await GitlabAPI.projects.repository.commits.al(projectId, { ref_name: 'branchName' });
