### ISSUE TITLE
customAttributes always undefined for user object

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#37]
I got a list of all users, by using 
```javascript
const users = await gitlab.users.all();
```

But getting custom attributes from one user, doesn't seem to work
```javascript
users.forEach((currentUser) => {
    console.log(currentUser.customAttributes.show());
}
```
```javascript
TypeError: Cannot read property 'show' of undefined
```

Any idea, what I might be doing wrong here?

**Comment by jdalrymple** [comment]
Hmm not sure. I'll look this weekend !! Finally got some spare time :D

**Comment by jdalrymple** [comment]
Found the problem! Will fix soon!

**Comment by jdalrymple** [comment]
So there was a bug in the custom attributes logic which i fixed, but currently the api wrapper doesnt actually return instances of each model from gitlab, it just wraps the api calls.

To get the custom attirbutes of a user, though its verbose, would be like this:

```javascript
const users = await gitlab.users.all();

await Promise.each(users, currentUser => {
    usersCustomAttributes = await gitlab.users.customAttributes.all(currentUser.id);
    console.log('usersCustomAttributes)
}

```

**Comment by jdalrymple** [comment]
IT would be really nice to return instances of the models, ill create an issue for it! It would be much more intuitive

**Comment by max-wittig** [comment]
Yes this clears things up. Thanks :)
