### ISSUE TITLE
How to access/create/update project and group level secret variables

### ISSUE THREAD

**Issue by saurabh-deep** [jdalrymple/node-gitlab-api#43]
Hi folks!

I am wondering if there is a way to access/create/update the project and group level secret variables. I looked through the code and couldn't find any models which are using variables related end points ([Project Level](https://docs.gitlab.com/ce/api/project_level_variables.html) and [Group Level](https://docs.gitlab.com/ce/api/group_level_variables.html)).

Appreciate your help!

Thanks
Saurabh

**Comment by jdalrymple** [comment]
Not at the moment, but I have been working on it for the next release :)

**Comment by jdalrymple** [comment]
Currently implementing this in the 3.0.0-beta branch. Still trying to settle on the API though, if you have any thoughts check out the branch and #38

**Comment by jdalrymple** [comment]
Released in the 3.0.0-beta release, will be making an official release soon. Need to do more testing :D

**Comment by jdalrymple** [comment]
Released in 3.0.0-rc.2
