### ISSUE TITLE
Add support for merge request approvals api

### ISSUE THREAD

**Issue by jnovick** [jdalrymple/node-gitlab-api#49]
GitLab 10.6 will be release tomorrow (3/22/18) and includes new endpoints for merge request approvals. I just want to submit a feature request for these routes to be added. https://docs.gitlab.com/ee/api/merge_request_approvals.html

**Comment by jdalrymple** [comment]
Just looking over the docs. How are these changes for the library

Projects
- showApprovals  (or approvals) -> gets config
-> editApprovals -> update config
-> editApprovers -> update approvers

Merge Requests
- showApprovals (or approvals) -> gets config
-> editApprovals -> update config
-> editApprovers -> update approvers
-> approve -> approve MR
-> unapprove -> unapprove MR

**Comment by jnovick** [comment]
I think that would be great! You responded ridiculously fast. I appreciate it. 👍

**Comment by jdalrymple** [comment]
Pushed in v3.0.0-rc.3

**Comment by Sryther** [comment]
It looks like the `approvals` method is not in the @gitbreaker/node v35.8.0 at least.
