### ISSUE TITLE
Complete API Support

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/node-gitlab-api#53]
As of writing this post, there are still many API's this library does not support. I would like to eventually tackle this remaining list for full support of the gitlab API:

- [x] Award
- [x] Emoji
- [x] Broadcast Messages
- [x] Deployments
- [x] Epics
- [x] Epic Issues
- [x] Feature flags
- [x] Geo Nodes
- [x] Gitignores templates
- [x] GitLab CI Config templates
- [x] Group Badges
- [x] Issue Boards
- [x] Group Issue Boards
- [x] License
- [x] Namespaces
- [x] Notes (comments) (Epics)
- [x] Discussions (threaded comments)
- [x] Notification settings
- [x] Open source license templates
- [x] Pages Domains
- [x] Pipeline Schedules
- [x] Project Badges
- [x] Project import/export
- [x] Search
- [x] Settings
- [x] Sidekiq metrics
- [x] Todos
- [x] Validate CI configuration
- [x] Wikis

**Comment by yuanoook** [comment]
and this https://docs.gitlab.com/ee/api/commits.html

**Comment by jdalrymple** [comment]
lol hard to keep up with new additions :P
