### ISSUE TITLE
basic auth url

### ISSUE THREAD

**Issue by shimont** [jdalrymple/node-gitlab-api#57]
When trying to connect to a GitLab with basic auth, the URL accessed is incorrect

Object instantiation: 
`const GitlabAPI = require('node-gitlab-api')({
  url: "https://username:password@gitlab.url.com/",
  token: "TOKEN"
})`

The request-promise url used to access GitLab:
`url: 'https://username:password@gitlab.url.com/api/v4/https://gitlab.url.com/api/v4/users?active=false&blocked=false&external=false&page=2&per_page=20',`

**Comment by jdalrymple** [comment]
That's weird. Will look today!

**Comment by jdalrymple** [comment]
https://docs.gitlab.com/ee/api/ Can you use basic auth to access the api ? Il fix the url, but I don't know if basic auth even works ?

**Comment by jdalrymple** [comment]
Oh, also which version of the library did you notice behaviour ?

**Comment by jdalrymple** [comment]
Nevermind, found it!

**Comment by jdalrymple** [comment]
Nevermind, i found it!

**Comment by jdalrymple** [comment]
The problem comes from the url that gitlab returns that links the pages. The link url doesnt maintain the basic auth information. I dont think basic auth is accepted by the Gitlab API. If it is, could you link the docs for that information please!

**Comment by shimont** [comment]
A good idea might be to allow the configuration of custom headers/options that will be passed to the request library - this way basic auth can be configured on the top level

**Comment by jdalrymple** [comment]
Could you direct me to the docs for basic authentication in the API ?

**Comment by shimont** [comment]
There are no docs regarding basic authentication - it is supported by the HTTP(s) protocol :)

**Comment by jdalrymple** [comment]
Yes but isn't supported by the gitlab api, so even if you add it in the url it will be stripped during pagination

**Comment by shimont** [comment]
I've made some tests, and if I put the object
`function defaultRequest(url, endpoint, {
  headers,
  body,
  qs,
  formData,
  resolveWithFullResponse = false
}) {
  const params = {
    url: (0, _urlJoin.default)(url, endpoint),
    headers,
    json: true,
    auth: { user: "USERNAME", pass: "PASSWORD" }
  };
  if (body) params.body = body;
  if (qs) params.qs = qs;
  if (formData) params.formData = formData;
  params.resolveWithFullResponse = resolveWithFullResponse;
  return params;
}` 
it works

Ill try to make a pull request with the option to pass custom auth parameters in the constructor

**Comment by jdalrymple** [comment]
I know you can add basic authentication, I'm asking if it is supported as an authentication method in the gitlab api. I've tested if you can access private data via basic authentication and I've been unsuccessful.

**Comment by shimont** [comment]
A client of my company has a GitLab API that has basic authentication via LDAP + token 
im working on a pull request that will support adding basic auth

**Comment by jdalrymple** [comment]
Ahhh that makes more sense. Sorry for the confusion! 

Yea that change wouldn't be hard to add! Just add the extra params to the library init

**Comment by jdalrymple** [comment]
Do you know of any docs related to LDAP auth with the API ? I've been looking at past issues, but i cant seen to find any. I wanna read up on how it works :)

**Comment by jdalrymple** [comment]
Is this related?

https://github.com/python-gitlab/python-gitlab/issues/380

**Comment by shimont** [comment]
I've gone through the links and they don't seem to be related.
In the case that I have, someone added basic HTTP authentication on top of the regular GitLab API to increase security.
In the pull request I submitted, I've added an option to add basic HTTP auth. it's not mandatory and shouldn't affect anyone that doesn't use it :)

**Comment by jdalrymple** [comment]
Ah so it doesn't have to do with gitlab at all, the customer just added basic authentication on top of their system. I think the addition then may be misleading. The options for basic authentication in the library makes it seem as if the API accepts basic authentication but it doesn't. 

Is this a common practice for self hosted gitlab users ? Seems like a custom solution.

**Comment by shimont** [comment]
I checked the setup with the client and it turns out that this is a custom solution they did by putting a Nginx with basic HTTP authentication in front of their GitLab. I can suggest that we add a global support for custom `request-promise` configuration - this way it won't be a specific fix and could help everyone. WDYT? if you approve - I can write it
Thanks

**Comment by bufferoverflow** [comment]
Support for such custom unsecure authentication methods should be handled outside of this library.

@shimont I recommend to get rid of this solution or implement a custom wrapper around this lib here that is handling the basic auth approach.

**Comment by jdalrymple** [comment]
Not to be a downer, but @bufferoverflow has a point :( maybe throw together a gitlab-headers library that allows for custom headers?

**Comment by gianniszach** [comment]
Hello, have you resolved this issue? I'm using basic authentication on-top of the hosted gitlab and if I use the basic auth credentials inside the URL I get an invalid concatenated in the request-promise. 

The basic auth scheme is applied on the web server hosting the gitlab service, it's not a part of gitlab as you've already said in the comments.

I've read the comments and I understand the argument that basic-auth is not a part of gitlab library, but I don't understand why this package will not handle the basic-auth requests. Isn't it the node-gitlab package's responsibility to connect to the web server which exposes the gitlab service? Doesn't it already handle the http connection to the gitlab server with the request-promise library? Why shouldn't it utilize the already existing code of basic-auth support provided by the request-promise library? And a final note, basic-auth was supported without any issues in older versions of this package, so deciding not to support it is like consciously making the decision to break backwards compatibility.

@bufferoverflow why do you think that http basic-auth mechanism is an insecure authentication method? Combining basic-auth with https gives you an extra layer of security on top of the web app's login form and as far as I know http basic-auth mechanism has never had any security issues.

**Comment by bufferoverflow** [comment]
@gianniszach Basic auth is a deployment specific solution and handling this should not be part of a library like this. Check https://www.google.com/search?q=basic+auth+deprecated to get an overview on the adoption rate of basic auth.

**Comment by gianniszach** [comment]
@bufferoverflow I'm sorry, I can't understand how something that is a part of the http rfc is a deployment specific solution. Basic auth is a part of the HTTP transaction and not a part of a deployment process.

As for the adoption rate, during the last years with the growth of APIs I've seen a great number of REST APIs utilizing basic auth as one of their authentication methods. Of course, this is irrelevant  to our issue, I'm just sending it because I feel like you're discarding basic auth and you're willing to break http compatibility without having a good enough reason.

**Comment by bufferoverflow** [comment]
Support for passing custom http headers such as for basic auth could be an option, but implement basic auth support does not belong to this library from my perspective.
