### ISSUE TITLE
Fails to minify when using create react app

### ISSUE THREAD

**Issue by jnovick** [jdalrymple/node-gitlab-api#66]
Can you provide an ES module entry point with the module field in package.json?

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by jnovick** [comment]
Here is my error message from the console: 

Failed to compile.

Failed to minify the code from this file:

        ../node_modules/node-gitlab-api/dist/latest/services/Events.js:16

Read more here: http://bit.ly/2tRViJ9

**Comment by jdalrymple** [comment]
WIll look into this tonight!

**Comment by jnovick** [comment]
I submitted a pull request since it is such a simple solution and it wouldn't break anything for existing users. If I am wron about backwards compatibility, let me know.
