### ISSUE TITLE
Issue time spent / time estimate

### ISSUE THREAD

**Issue by MrSnoozles** [jdalrymple/node-gitlab-api#68]
Hello,

I was looking for a way to add time estimates and spent times for issues through the API. I could find methods to add time for merge requests, but not for individual issues so I guess it is not implemented. Is that right?

If so, would you need help implementing it? I guess it would take me some time though to understand how this library works, but I'd be happy to help.

The relevant documentation can be found here 
https://docs.gitlab.com/ee/api/issues.html#add-spent-time-for-an-issue

Regards
Alex

**Comment by jdalrymple** [comment]
Yup! I must of missed that. Easy thing to add, shouldnt take me more than a minute :)

**Comment by jdalrymple** [comment]
Merged and published :) hope this helps!

**Comment by MrSnoozles** [comment]
Write an issue before going to bed, have a solution when you wake up. This is like Christmas for developers. 

Thank you so much. From what I could test it seems to be working splendidly.
