### ISSUE TITLE
UserCustomAttributes gone?

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#69]
I've used node-gitlab-api 2.2.6 before, which was really intuitive imo (similar to python-gitlab)

Now I wanted to switch to 3.1.0 and I find the new syntax is really confusing. I really need every feature of the GitLab API in one node program. Should I now create a new instance for every bundle?

Also I cannot seem to find any documentation about the custom attributes for Users. I just found the subservice in the User bundle, which I need to initialize as another instance?

Thanks for any help

**Comment by jdalrymple** [comment]
Just published, should be fixed now :)

**Comment by max-wittig** [comment]
Awesome thank you! @jdalrymple
