### ISSUE TITLE
Problems with current npm release

### ISSUE THREAD

**Issue by keiranmraine** [jdalrymple/node-gitlab-api#74]
If I attempt to use the current NPM release (3.0.2, `npm i --save node-gitlab-api`) with the `ProjectsBundle` constructor I get the following error:

```
(node:55285) UnhandledPromiseRejectionWarning: TypeError: _nodeGitlabApi.ProjectsBundle is not a constructor
```

```js
import { ProjectsBundle } from 'node-gitlab-api';
...
const api = new ProjectsBundle({
    url: gitlabUrl,
    token: gitlabToken
  });
```

I did try the alternate `gitlab` entry from npm (appears to be ahead of your releases at 3.2.0) and installing using the git tag results in node being unable to find the module (in both cases I update the import to `gitlab`).

Importing `Gitlab` seems fine so I'm sure I'm missing something obvious.

**Comment by jdalrymple** [comment]
Hmm I'll look today :)

**Comment by jdalrymple** [comment]
Should be fixed now, please stick to the gitlab npm package for now, the node-gitlab-api one has been deprecated and wont be updated.
