### ISSUE TITLE
Version API not working?

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab-api#79]
Seems like the version information is not properly exposed anymore. Is that true or am I using this feature wrong?

```
node-gitlab-api version: 3.2.1
runtime: node v8.11.1
```

```javascript
const Gitlab = require('gitlab').default;
console.log(gitlab.Version);
undefined
```

**Comment by jdalrymple** [comment]
hmm, not sure whats going on there. Will look today!!

**Comment by jdalrymple** [comment]
For whatever reason its missing from the exports. ill publish the fix in a few hours

**Comment by jdalrymple** [comment]
Should be good now!
