### ISSUE TITLE
Why is it not require('gitlab/dist/es5') ?

### ISSUE THREAD

**Issue by imraazrally** [jdalrymple/node-gitlab-api#80]
Hey, the documentation says 
`const Gitlab = require('node-gitlab-api/dist/es5').default`

and why not `require('gitlab/dist/es5')` ?

**Comment by jdalrymple** [comment]
When I wrote the docs and was testing it wasn't working for me lol. I can check again?

**Comment by imraazrally** [comment]
Yeah, it wasn't working for me either lol I think the bug i was getting was related to async/await code. This ticket is not urgent and i'm happy to use the node-gitlab-api 3.0.22 in the meanwhile. But i did alot of debugging for #81 and can't seem to figure out what is going on. I'd be super appreciative if you can check that and see if you catch anything i haven't :)

**Comment by jdalrymple** [comment]
https://stackoverflow.com/questions/42475691/importing-vs-requiring-with-babel-in-node Here is an explaination of why there is a default.

**Comment by jdalrymple** [comment]
and here https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/

**Comment by jdalrymple** [comment]
Tried to add the plugin https://www.npmjs.com/package/babel-plugin-add-module-exports to remove the verbosity, but i didnt have much luck

**Comment by imraazrally** [comment]
Hey, i think i didn't communicate this properly. What i was specifically wondering is when i do a `require('gitlab/dist/es5')` (as opposed to `node-gitlab-api/dist/es5`) i am having issues. This forces me to stick to `node-gitlab-api` of version 3.0.2. but most of the new fixes you put in place such as #82 is only available in `gitlab` library. 

Code:
```
const Gitlab = require('gitlab/dist/es5').default
const client = new Gitlab({
  url:   'https://gitlab.com', // Defaults to http://gitlab.com
  token: 'tG4dZ9UUwijyQKoaZZE2'	// Can be created in your profile.
})
const response = await client.Projects.all({membership: true, page:1, per_page: 1});
``` 

Bug:
```
/Users/irally1/Desktop/test/node_modules/gitlab/dist/es5/infrastructure/XMLHttpRequester.js:18
  return async function (opts) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
...
```

Thanks, much appreciated!

**Comment by jdalrymple** [comment]
AHHH, ill fix this sorry!

**Comment by imraazrally** [comment]
Thanks, created a new issue #84
